services:
  mysql:
    image: mysql:8.0
    container_name: sql-fatec-bd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
